# Generated by Django 3.2.25 on 2024-06-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240611_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingreidnet',
            new_name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingreidnets',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='core.Ingredient'),
        ),
    ]
